services:
  - type: web
    name: restaurant-website
    env: python
    buildCommand: 
      pip install -r requirements.txt
    startCommand: gunicorn restaurant.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: restaurant.settings
      - key: PYTHON_VERSION
        value: python-3.12.3
